# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Victoria Avis
email:
description: >- # this means to ignore newlines until "baseurl:"
  Victoria Avis' work explores international development, political theory, and urban planning in Global South contexts. 
keywords: >-
  Victoria Avis, Victoria, Avis, Tori Avis, MIT, Massachusetts Institute of Technology, DUSP, 
  Department of Urban Studies and Planning, Department of Urban Studies & Planning, MIT SA+P, 
  MIT School of Architecture and Planning, MIT School of Architecture & Planning, 
  The George Washington University, George Washington University, GW, GWU, ESIA, 
  Elliott School of International Affairs, Elliott School of International Affairs at The George Washington University, 
  USAID, Falmouth Academy, FA, United States Agency for International Development, Africa, sub-Saharan Africa, 
  SSA, urban planning, international development, urbanization, political theory, urban theory, critical urban theory, 
  critical development theory, critical development studies, foreign policy, US foreign policy, 
  U.S. foreign policy, geopolitics, strategy, geopolitical strategy, international affairs, international relations, 
  IA, IR, MCP, USG, infrastructure, political science, global affairs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victoria-avis.com" # the base hostname & protocol for your site, e.g. http://example.com
pathToImgBin: /assets/img/

github:  
linkedin: https://www.linkedin.com/in/victoriaavis/
google_scholar: 

highlighter: rouge

# Build settings
permalink: pretty
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-autoprefixer
exclude: 
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass